name: notes_plus
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_bloc: ^8.1.3

  # Data
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2

  # Utils
  uuid: ^4.3.3
  equatable: ^2.0.5
  intl: ^0.19.0
  cron: ^0.6.0
  connectivity_plus: ^6.0.5

  # Firebase
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.1.11


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffbf00"
  web:
    generate: true
    background_color: "#ffbf00"
    theme_color: "#ffbf00"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
