// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoB9NahDoP5k_sKyfeKQCkexvdszd8tS4',
    appId: '1:356770001639:web:26280658e4323092e36842',
    messagingSenderId: '356770001639',
    projectId: 'girman-6ca70',
    authDomain: 'girman-6ca70.firebaseapp.com',
    storageBucket: 'girman-6ca70.appspot.com',
    measurementId: 'G-8FHTDJMRW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDowd7YBxf531GulmE_AZg7SYVMcMVhbuI',
    appId: '1:356770001639:android:1f959330a36f0720e36842',
    messagingSenderId: '356770001639',
    projectId: 'girman-6ca70',
    storageBucket: 'girman-6ca70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATjrIKZP-LqMZPeELwm98xtcS_Hn4dSis',
    appId: '1:356770001639:ios:ca7bd66d5a2215f5e36842',
    messagingSenderId: '356770001639',
    projectId: 'girman-6ca70',
    storageBucket: 'girman-6ca70.appspot.com',
    iosBundleId: 'com.example.notesPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATjrIKZP-LqMZPeELwm98xtcS_Hn4dSis',
    appId: '1:356770001639:ios:ca7bd66d5a2215f5e36842',
    messagingSenderId: '356770001639',
    projectId: 'girman-6ca70',
    storageBucket: 'girman-6ca70.appspot.com',
    iosBundleId: 'com.example.notesPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoB9NahDoP5k_sKyfeKQCkexvdszd8tS4',
    appId: '1:356770001639:web:f6cd1504f6de6dbbe36842',
    messagingSenderId: '356770001639',
    projectId: 'girman-6ca70',
    authDomain: 'girman-6ca70.firebaseapp.com',
    storageBucket: 'girman-6ca70.appspot.com',
    measurementId: 'G-KTKPNH9P49',
  );
}
